version: "~> 1.0"
os: linux
dist: xenial
language: python
python:
  - '3.6'
services:
  - docker
notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    if: branch = master
    rooms:
      secure: cJA9mUDsJzsDvSoC2UywSLNb1MWEtvLwXG0C8mQPyNTiWuC1Tjh09SIFr3WKNlzkp8GGGxELKo4lNlDNoWwB/wVjSZfHxU3INXNe+6lppCxfvqLYRZX+QtsFogaYRZP2kv6D61JUvkEn43CvRYIxZQ4ondXtJF8dnhrePON3NH6U5oqlQ/ytX8yWjUsu8nxOz4JjGUch6AX6xvd+TT3sD5Lm0PBLRMEUvqPcPfgv8TjQbOVtUb/vUqXrQMkdC+QdTm9xeFq5eTYOoNZVUd/NGj7gf6/wrcBAMjksRSns2HVB4AgsQJtZ8IdKFF5UcVSEHXUr/NYdgxz4EbtU55ORiEH6K1CNwD8FG95IE2JqV+hAUU7qecfXBgZVTfWnMSA78bTQwuMyTimjWBzdAgvyLuO6+w8askCyR3Gsf5KNK1Efll+6eMwRUjK+5hhnhF4LltnKyHc0lW60AGNr+2ZGNGMUw3+GW+NSbjwgMNGIa3yU6O0Arjj1pgRt75WjhJbgTGXU+hn6TOm0MQd+BnA4q1Zg7d52HvnGWSFi013sDmQKEQGCcB+xheYKO0Z2zCElCoNtqH5aRjeQATlLh7B+03tdQxecCGdv2If9W4qNhrYXFPmJrY8ZJX/JsEhEVE4kQb3du8MBjWoUx1Co5mab3tjFbDXo49g82uKAItpUipg=
    template:
      - "%{commit_subject}"
      - build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) @%{branch}
      - by %{author} %{result} in %{duration}
    on_success: change
    on_failure: always
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
install:
  - pip install -r requirements.txt
env:
  jobs:
    - SCENARIO=default
script:
  - molecule test --scenario-name ${SCENARIO}
